# Generated by Django 3.2.9 on 2022-07-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(max_length=30)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=110)),
                ('Email_Id', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
