# Generated by Django 3.2.9 on 2022-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='Adress',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Confirm_Password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Password',
            field=models.CharField(max_length=30),
        ),
    ]
