# Generated by Django 3.2.9 on 2022-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220725_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='profile_imgs/download.jpg', upload_to='profile_imgs/'),
        ),
    ]
